'use client'

import { useState, useEffect } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { 
  Globe, 
  ExternalLink, 
  Save, 
  CheckCircle, 
  AlertCircle,
  Link2,
  Sparkles,
  Info,
  Copy
} from 'lucide-react';
import { toast } from 'sonner';

interface ManualGoogleReviewLinkProps {
  clinicId: string;
  googlePlaceId?: string | null;
}

export default function ManualGoogleReviewLink({ clinicId, googlePlaceId }: ManualGoogleReviewLinkProps) {
  const queryClient = useQueryClient();
  const [customReviewUrl, setCustomReviewUrl] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);

  // Auto-generate the Google Review URL if we have a place ID
  const autoGeneratedUrl = googlePlaceId
    ? `https://search.google.com/local/writereview?placeid=${googlePlaceId}`
    : '';

  // Fetch existing custom review URL from clinic_oauth_tokens
  useEffect(() => {
    const fetchCustomUrl = async () => {
      // First try clinic_oauth_tokens (new secure table)
      const { data: tokenData } = await supabase
        .from('clinic_oauth_tokens')
        .select('gmb_data')
        .eq('clinic_id', clinicId)
        .single();
      
      if (tokenData?.gmb_data && typeof tokenData.gmb_data === 'object') {
        const gmbData = tokenData.gmb_data as { custom_review_url?: string };
        if (gmbData.custom_review_url) {
          setCustomReviewUrl(gmbData.custom_review_url);
        }
      }
    };
    
    fetchCustomUrl();
  }, [clinicId]);

  const handleSave = async () => {
    if (!customReviewUrl.trim()) {
      toast.error('Please enter a valid review URL');
      return;
    }

    // Basic URL validation
    try {
      new URL(customReviewUrl);
    } catch {
      toast.error('Please enter a valid URL (e.g., https://g.page/r/...)');
      return;
    }

    setIsSaving(true);
    try {
      // Get existing gmb_data from clinic_oauth_tokens
      const { data: existing } = await supabase
        .from('clinic_oauth_tokens')
        .select('gmb_data')
        .eq('clinic_id', clinicId)
        .single();

      const existingData = (existing?.gmb_data as Record<string, unknown>) || {};
      
      // Update or insert with custom review URL
      const { error } = await supabase
        .from('clinic_oauth_tokens')
        .upsert({
          clinic_id: clinicId,
          gmb_data: {
            ...existingData,
            custom_review_url: customReviewUrl.trim(),
          },
        }, {
          onConflict: 'clinic_id'
        });

      if (error) throw error;

      toast.success('Review link saved successfully!');
      queryClient.invalidateQueries({ queryKey: ['dentist-clinic-reputation'] });
    } catch (error: any) {
      toast.error(error.message || 'Failed to save review link');
    } finally {
      setIsSaving(false);
    }
  };

  const copyLink = async (url: string) => {
    try {
      await navigator.clipboard.writeText(url);
      setLinkCopied(true);
      toast.success('Link copied!');
      setTimeout(() => setLinkCopied(false), 2000);
    } catch {
      toast.error('Failed to copy');
    }
  };

  const effectiveReviewUrl = customReviewUrl || autoGeneratedUrl;

  return (
    <Card className="bg-slate-800/90 border border-slate-700/50 shadow-lg overflow-hidden">
      <div className="h-1 bg-gradient-to-r from-gold via-primary to-gold" />
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg flex items-center gap-2 text-white">
              <Globe className="h-5 w-5 text-gold" />
              Google Review Capture Link
            </CardTitle>
            <CardDescription className="text-white/60 mt-1">
              Where positive feedback gets redirected
            </CardDescription>
          </div>
          {googlePlaceId ? (
            <Badge className="bg-teal/20 text-teal border-teal/30 border">
              <CheckCircle className="h-3 w-3 mr-1" />
              GMB Connected
            </Badge>
          ) : (
            <Badge className="bg-gold/20 text-gold border-gold/30 border">
              <AlertCircle className="h-3 w-3 mr-1" />
              Manual Mode
            </Badge>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Info Box */}
        <div className="p-3 rounded-xl bg-slate-900/50 border border-slate-700/50">
          <div className="flex items-start gap-3">
            <Info className="h-4 w-4 text-primary mt-0.5 shrink-0" />
            <p className="text-xs text-white/70 leading-relaxed">
              {googlePlaceId 
                ? "Your Google Place ID is connected. Positive feedback will redirect to Google Reviews. You can override this with a custom link below."
                : "Add your Google Review link manually. When patients give positive feedback, they'll be redirected to this URL to leave a public review."
              }
            </p>
          </div>
        </div>

        {/* Auto-generated URL (if GMB connected) */}
        {googlePlaceId && autoGeneratedUrl && !customReviewUrl && (
          <div className="space-y-2">
            <Label className="text-sm text-white/70 flex items-center gap-2">
              <Sparkles className="h-3.5 w-3.5 text-teal" />
              Auto-Generated Link
            </Label>
            <div className="flex gap-2">
              <Input 
                value={autoGeneratedUrl}
                readOnly
                className="bg-slate-900/50 border-slate-600/50 text-white text-sm font-mono"
              />
              <Button 
                variant="outline" 
                size="icon" 
                className="border-slate-600/50 hover:bg-slate-700/50 shrink-0"
                onClick={() => copyLink(autoGeneratedUrl)}
              >
                {linkCopied ? <CheckCircle className="h-4 w-4 text-teal" /> : <Copy className="h-4 w-4 text-white" />}
              </Button>
              <Button 
                variant="outline" 
                size="icon"
                className="border-slate-600/50 hover:bg-slate-700/50 shrink-0"
                asChild
              >
                <a href={autoGeneratedUrl} target="_blank" rel="noopener noreferrer">
                  <ExternalLink className="h-4 w-4 text-white" />
                </a>
              </Button>
            </div>
          </div>
        )}

        {/* Custom/Manual URL Input */}
        <div className="space-y-2">
          <Label className="text-sm text-white/70 flex items-center gap-2">
            <Link2 className="h-3.5 w-3.5 text-gold" />
            {googlePlaceId ? 'Custom Override Link (Optional)' : 'Your Google Review Link'}
          </Label>
          <div className="flex gap-2">
            <Input
              value={customReviewUrl}
              onChange={(e) => setCustomReviewUrl(e.target.value)}
              placeholder="https://g.page/r/your-business/review"
              className="bg-slate-900/50 border-slate-600/50 text-white placeholder:text-white/40 text-sm"
            />
            <Button
              onClick={handleSave}
              disabled={isSaving}
              className="bg-gold hover:bg-gold/90 text-slate-900 font-semibold shrink-0"
            >
              {isSaving ? (
                <>Saving...</>
              ) : (
                <>
                  <Save className="h-4 w-4 mr-2" />
                  Save
                </>
              )}
            </Button>
          </div>
          <p className="text-xs text-white/50">
            Find your link at{' '}
            <a 
              href="https://support.google.com/business/answer/7035772" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              Google Business Profile → Share Review Link
            </a>
          </p>
        </div>

        {/* Current Active Link Display */}
        {effectiveReviewUrl && (
          <div className="pt-3 border-t border-slate-700/50">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-teal" />
                <span className="text-sm text-white/70">Active redirect:</span>
              </div>
              <a 
                href={effectiveReviewUrl} 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-sm text-primary hover:underline flex items-center gap-1 max-w-[300px] truncate"
              >
                {effectiveReviewUrl.length > 40 
                  ? effectiveReviewUrl.substring(0, 40) + '...' 
                  : effectiveReviewUrl
                }
                <ExternalLink className="h-3 w-3 shrink-0" />
              </a>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}