-- Insert all standard dental treatments
INSERT INTO treatments (name, slug, description, display_order, is_active) VALUES
  ('General Dentistry', 'general-dentistry', 'Routine dental care including exams, cleanings, and preventive treatments', 1, true),
  ('Teeth Cleaning', 'teeth-cleaning', 'Professional dental cleaning to remove plaque and tartar buildup', 2, true),
  ('Dental Checkup', 'dental-checkup', 'Comprehensive oral examination to assess dental health', 3, true),
  ('Dental Fillings', 'dental-fillings', 'Restoration of teeth damaged by decay using composite or amalgam materials', 4, true),
  ('Root Canal Treatment', 'root-canal-treatment', 'Endodontic therapy to treat infected tooth pulp and save the tooth', 5, true),
  ('Tooth Extraction', 'tooth-extraction', 'Removal of damaged or problematic teeth', 6, true),
  ('Wisdom Teeth Removal', 'wisdom-teeth-removal', 'Surgical extraction of third molars', 7, true),
  ('Dental Crowns', 'dental-crowns', 'Custom-made caps to restore damaged teeth', 8, true),
  ('Dental Bridges', 'dental-bridges', 'Fixed prosthetic devices to replace missing teeth', 9, true),
  ('Dentures', 'dentures', 'Removable replacements for missing teeth', 10, true),
  ('Dental Implants', 'dental-implants', 'Permanent tooth replacement with titanium posts', 11, true),
  ('Teeth Whitening', 'teeth-whitening', 'Professional bleaching to brighten and whiten teeth', 12, true),
  ('Dental Veneers', 'dental-veneers', 'Thin shells bonded to teeth for cosmetic improvement', 13, true),
  ('Invisalign', 'invisalign', 'Clear aligner therapy for teeth straightening', 14, true),
  ('Braces', 'braces', 'Orthodontic treatment to correct teeth alignment', 15, true),
  ('Cosmetic Dentistry', 'cosmetic-dentistry', 'Aesthetic dental procedures to improve smile appearance', 16, true),
  ('Smile Makeover', 'smile-makeover', 'Comprehensive cosmetic treatment plan for complete smile transformation', 17, true),
  ('Gum Treatment', 'gum-treatment', 'Periodontal therapy for gum disease and infections', 18, true),
  ('Deep Cleaning', 'deep-cleaning', 'Scaling and root planing for periodontal health', 19, true),
  ('Pediatric Dentistry', 'pediatric-dentistry', 'Dental care specialized for children', 20, true),
  ('Emergency Dental Care', 'emergency-dental-care', 'Urgent treatment for dental emergencies and pain', 21, true),
  ('TMJ Treatment', 'tmj-treatment', 'Therapy for temporomandibular joint disorders', 22, true),
  ('Dental X-Rays', 'dental-x-rays', 'Diagnostic imaging for comprehensive dental assessment', 23, true),
  ('Fluoride Treatment', 'fluoride-treatment', 'Preventive application to strengthen tooth enamel', 24, true),
  ('Dental Sealants', 'dental-sealants', 'Protective coatings applied to prevent cavities', 25, true),
  ('Night Guards', 'night-guards', 'Custom mouthguards to prevent teeth grinding', 26, true),
  ('Sports Mouthguards', 'sports-mouthguards', 'Protective dental appliances for athletic activities', 27, true),
  ('Sedation Dentistry', 'sedation-dentistry', 'Anxiety-free dental treatment with sedation options', 28, true),
  ('All-on-4 Implants', 'all-on-4-implants', 'Full arch restoration with just four dental implants', 29, true),
  ('Bone Grafting', 'bone-grafting', 'Surgical procedure to rebuild jawbone for implants', 30, true),
  ('Gum Contouring', 'gum-contouring', 'Reshaping gum line for improved aesthetics', 31, true),
  ('Dental Bonding', 'dental-bonding', 'Tooth-colored resin application to repair chips and gaps', 32, true),
  ('Inlays and Onlays', 'inlays-onlays', 'Custom-made restorations for moderate tooth decay', 33, true),
  ('Full Mouth Reconstruction', 'full-mouth-reconstruction', 'Comprehensive restoration of all teeth', 34, true),
  ('Laser Dentistry', 'laser-dentistry', 'Advanced dental procedures using laser technology', 35, true)
ON CONFLICT (slug) DO NOTHING;