-- UK Cities Seed - Expanded to 50+ cities
INSERT INTO cities (name, slug, is_active) VALUES
-- England - Major Cities
('London', 'london', true),
('Birmingham', 'birmingham', true),
('Manchester', 'manchester', true),
('Leeds', 'leeds', true),
('Liverpool', 'liverpool', true),
('Sheffield', 'sheffield', true),
('Bristol', 'bristol', true),
('Newcastle', 'newcastle', true),
('Nottingham', 'nottingham', true),
('Leicester', 'leicester', true),
('Southampton', 'southampton', true),
('Brighton', 'brighton', true),
('Hull', 'hull', true),
('Bradford', 'bradford', true),
('Stoke-on-Trent', 'stoke-on-trent', true),
('Wolverhampton', 'wolverhampton', true),
('Derby', 'derby', true),
('Sunderland', 'sunderland', true),
('Warrington', 'warrington', true),
('York', 'york', true),
('Peterborough', 'peterborough', true),
('Southend-on-Sea', 'southend-on-sea', true),
('Chelmsford', 'chelmsford', true),
('Bournemouth', 'bournemouth', true),
(' Middlesbrough', 'middlesbrough', true),
('Oxford', 'oxford', true),
('Maidstone', 'maidstone', true),
('Slough', 'slough', true),
('Cambridge', 'cambridge', true),
('Guildford', 'guildford', true),
('Eastbourne', 'eastbourne', true),
('Wexham', 'wexham', true),
('Chichester', 'chichester', true),
('Durham', 'durham', true),
('St Albans', 'st-albans', true),
('Luton', 'luton', true),
('Doncaster', 'doncaster', true),
('Basildon', 'basildon', true),
('Wigan', 'wigan', true),
('Stockport', 'stockport', true),
('Shrewsbury', 'shrewsbury', true),
('Salford', 'salford', true),
('Macclesfield', 'macclesfield', true),
('Kingston upon Hull', 'kingston-upon-hull', true),
-- Scotland
('Edinburgh', 'edinburgh', true),
('Glasgow', 'glasgow', true),
('Aberdeen', 'aberdeen', true),
('Dundee', 'dundee', true),
('Inverness', 'inverness', true),
-- Wales
('Cardiff', 'cardiff', true),
('Swansea', 'swansea', true),
('Newport', 'newport', true),
('Wrexham', 'wrexham', true),
-- Northern Ireland
('Belfast', 'belfast', true),
('Derry', 'derry', true),
('Newtownards', 'newtownards', true)
ON CONFLICT (slug) DO NOTHING;